name: Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Set environment variables
      run: |
        echo "ARM64_APK_SHA256=$(sha256sum app/build/outputs/apk/release/*-arm64-v8a-release.apk | awk '{ print $1 }')" >> $GITHUB_ENV
        echo "X86_64_APK_SHA256=$(sha256sum app/build/outputs/apk/release/*-x86_64-release.apk | awk '{ print $1 }')" >> $GITHUB_ENV

    - name: Get apk info
      id: apk-info
      uses: hkusu/apk-info-action@v1
      with:
        apk-path: app/build/outputs/apk/release/app-arm64-v8a-release.apk

    - name: Upload binaries to a release
      uses: softprops/action-gh-release@v1
      with:
        body: |
          ## SHA-256 Checksums of APKs
          * **arm64-v8a**: `${{ env.ARM64_APK_SHA256 }}`
          * **x86_64**: `${{ env.X86_64_APK_SHA256 }}`
        files: app/build/outputs/apk/release/*.apk
        tag_name: v${{ steps.apk-info.outputs.version-name }}
